language: node_js
node_js:
  - "4.0"
script:
  - echo "Deploying..."
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token 1/tY85eT-sA9cgvxgqL1mtCYxF_FBkftXrkspO5eE7sZI